version: "2"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - revive
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
  settings:
    gofmt:
      simplify: true
    govet:
      enable:
        - shadow

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
