# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: tiny-auth
    binary: tiny-auth
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.Date}}
      - -X main.gitCommit={{.Commit}}
    mod_timestamp: "{{.CommitTimestamp}}"

archives:
  - id: tiny-auth
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - config.example.toml

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{.Version}}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: "New Features"
      regexp: "^feat:"
    - title: "Bug Fixes"
      regexp: "^fix:"
    - title: "Security"
      regexp: "^security:"
    - title: "Others"
      order: 999

dockers:
  # GHCR (GitHub Container Registry) - amd64
  - image_templates:
      - "ghcr.io/nerdneilsfield/{{.ProjectName}}:{{.Version}}-amd64"
      - "ghcr.io/nerdneilsfield/{{.ProjectName}}:latest-amd64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - config.example.toml
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.description="A lightweight authentication service for Traefik ForwardAuth"
      - --label=org.opencontainers.image.url=https://github.com/nerdneilsfield/{{.ProjectName}}
      - --label=org.opencontainers.image.source=https://github.com/nerdneilsfield/{{.ProjectName}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.licenses=MIT

  # GHCR - arm64
  - image_templates:
      - "ghcr.io/nerdneilsfield/{{.ProjectName}}:{{.Version}}-arm64"
      - "ghcr.io/nerdneilsfield/{{.ProjectName}}:latest-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - config.example.toml
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.description="A lightweight authentication service for Traefik ForwardAuth"
      - --label=org.opencontainers.image.url=https://github.com/nerdneilsfield/{{.ProjectName}}
      - --label=org.opencontainers.image.source=https://github.com/nerdneilsfield/{{.ProjectName}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.licenses=MIT

  # Docker Hub - amd64
  - image_templates:
      - "nerdneils/{{.ProjectName}}:{{.Version}}-amd64"
      - "nerdneils/{{.ProjectName}}:latest-amd64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - config.example.toml
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.description="A lightweight authentication service for Traefik ForwardAuth"
      - --label=org.opencontainers.image.url=https://github.com/nerdneilsfield/{{.ProjectName}}
      - --label=org.opencontainers.image.source=https://github.com/nerdneilsfield/{{.ProjectName}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.licenses=MIT

  # Docker Hub - arm64
  - image_templates:
      - "nerdneils/{{.ProjectName}}:{{.Version}}-arm64"
      - "nerdneils/{{.ProjectName}}:latest-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - config.example.toml
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.description="A lightweight authentication service for Traefik ForwardAuth"
      - --label=org.opencontainers.image.url=https://github.com/nerdneilsfield/{{.ProjectName}}
      - --label=org.opencontainers.image.source=https://github.com/nerdneilsfield/{{.ProjectName}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
  # GHCR manifests
  - name_template: "ghcr.io/nerdneilsfield/{{.ProjectName}}:{{.Version}}"
    image_templates:
      - "ghcr.io/nerdneilsfield/{{.ProjectName}}:{{.Version}}-amd64"
      - "ghcr.io/nerdneilsfield/{{.ProjectName}}:{{.Version}}-arm64"
  - name_template: "ghcr.io/nerdneilsfield/{{.ProjectName}}:latest"
    image_templates:
      - "ghcr.io/nerdneilsfield/{{.ProjectName}}:latest-amd64"
      - "ghcr.io/nerdneilsfield/{{.ProjectName}}:latest-arm64"

  # Docker Hub manifests
  - name_template: "nerdneils/{{.ProjectName}}:{{.Version}}"
    image_templates:
      - "nerdneils/{{.ProjectName}}:{{.Version}}-amd64"
      - "nerdneils/{{.ProjectName}}:{{.Version}}-arm64"
  - name_template: "nerdneils/{{.ProjectName}}:latest"
    image_templates:
      - "nerdneils/{{.ProjectName}}:latest-amd64"
      - "nerdneils/{{.ProjectName}}:latest-arm64"

release:
  github:
    owner: nerdneilsfield
    name: tiny-auth
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## tiny-auth {{.Tag}}

    A lightweight authentication service for Traefik ForwardAuth.

    ### Installation

    **Docker:**
    ```bash
    docker pull ghcr.io/nerdneilsfield/tiny-auth:{{.Tag}}
    ```

    **Binary Download:**
    Download the appropriate binary for your platform from the assets below.

  footer: |
    ## What's Changed
    **Full Changelog**: https://github.com/nerdneilsfield/tiny-auth/compare/{{.PreviousTag}}...{{.Tag}}
